// =============================================================
// product.types.ts — here we define the "shape" of our data
// -------------------------------------------------------------
// .NET analogy: these are like C# Model / DTO classes.
// An interface only describes "which properties an object has and
// of what type". Remember: this is compile-time only — it disappears
// from the JavaScript after the build.
// =============================================================

// A full Product — exactly as it comes from the server (json-server).
export interface Product {
  id: number; // unique id (generated by the server)
  name: string;
  description: string;
  price: number;
  inStock: boolean; // is it in stock? (true/false)
}

// What the user fills in the form. There is no `id` here, because when
// creating a new product the id does not exist yet (the server makes it).
export interface ProductFormData {
  name: string;
  description: string;
  price: number;
  inStock: boolean;
}

/* =============================================================
   📝 INTERVIEW Q&A — TypeScript Types / Interface
   -------------------------------------------------------------
   Q1. Difference between interface and type?
   → Both describe the shape of an object. interface is easy to "extend"
     and merges when declared twice with the same name (declaration
     merging). `type` can also do unions (A | B), primitive aliases,
     tuples, etc. For object models, interface is the common choice.

   Q2. Why are Product and ProductFormData separate?
   → Product has `id` (given by the server), but the create form has no
     id. Keeping them separate means accidentally sending an id is caught
     at compile time.

   Q3. Do interfaces exist at runtime?
   → No. TypeScript only checks at dev/compile time; after the build all
     types are erased and the browser runs plain JavaScript. So types
     cannot do runtime validation — for that you need a library like
     zod / yup.

   Q4. How do you make a property optional?
   → Put `?` after the name. e.g. `description?: string;` means it may or
     may not be present (its type becomes `string | undefined`).

   Q5. What happens if an interface like `interface Product {}` is empty?
   → It matches almost any non-null object, so empty interfaces are best
     avoided.
   ============================================================= */
